(
  (context gitui)

  (inject view GitUiView "getGitUiView()")

  (command toggle gitUiToggle [] () "Toggle git ui")
  (command cursor-down gitUiCursorDown [] () "Move cursor down")
  (command cursor-up gitUiCursorUp [] () "Move cursor up")
  (command push gitUiPush [] () "Push")
  (command pull gitUiPull [] () "Pull")
  (command stash gitUiStash [] () "Stash changes")
  (command stash-pop gitUiStashPop [] () "Pop latest stash")
  (command commit gitUiCommit [] () "Commit")
  (command commit-amend gitUiCommitAmend [] () "Amend latest commit")
  (command commit-edit-start gitUiCommitEditStart [] () "Start editing commit message")
  (command commit-edit-cancel gitUiCommitEditCancel [] () "Cancel editing commit message")
  (command commit-edit-confirm gitUiCommitEditConfirm [] () "Confirm commit message")
  (command switch-branch gitUiSwitchBranch [] () "Switch branch")
  (command fetch gitUiFetch [] () "Fetch")
  (command reset-soft gitUiResetSoft [] () "Soft reset")
  (command stage-all gitUiStageAll [] () "Stage all files")
  (command stage-selected gitUiStageSelected [] () "Stage selected file")
  (command unstage-selected gitUiUnstageSelected [] () "Unstage selected file")
  (command revert-selected gitUiRevertSelected [] () "Revert selected file")
  (command diff-selected gitUiDiffSelected [] () "Diff selected file, commit or stash")
  (command refresh gitUiRefresh [] () "Refresh UI")
)