(
  (context vim)

  (command exit-command-line exitCommandLine [] () "")
  (command exit-popup exitPopup [] () "")
  (command last-popup-next lastPopupNext [] () "")
  (command last-popup-prev lastPopupPrev [] () "")
  (command mode-changed-handler modeChangedHandler [(editorId EditorIdNew) (oldModes "seq[string]") (newModes "seq[string]")] () "")

  (inject (self TextEditor))

  (active-command handle-select-word handleSelectWord [(cursor Cursor)] () "")
  (active-command select-line selectLine [] () "")
  (active-command normal-mode normalMode [] () "")
  (active-command visual-mode visualMode [] () "")
  (active-command visual-line-mode visualLineMode [] () "")
  (active-command select-last selectLast [(move string) (count int 0)] () "")
  (active-command select select [(move string) (count int 1)] () "")
  (active-command undo undo [(enterNormalModeBefore bool)] () "")
  (active-command redo redo [(enterNormalModeBefore bool)] () "")
  (active-command delete-selection deleteSelection [(forceInclusiveEnd bool) (oldSelections "Option[seq[Selection]]" ("seq[Selection].none")) (forceExclusive bool false)] () "")
  (active-command change-selection changeSelection [(forceInclusiveEnd bool) (oldSelections "Option[seq[Selection]]" ("seq[Selection].none")) (forceExclusive bool false)] () "")
  (active-command yank-selection yankSelection [(inclusive bool true)] () "")
  (active-command yank-selection-clipboard yankSelectionClipboard [(inclusive bool true)] () "")
  (active-command replace replace [(input string)] () "")
  (active-command select-move selectMove [(move string) (count int 0)] () "")
  (active-command delete-move deleteMove [(move string) (count int 0)] () "")
  (active-command change-move changeMove [(move string) (count int 0)] () "")
  (active-command yank-move yankMove [(move string) (count int 0)] () "")
  (active-command select-text-object selectTextObject [(textObject string) (count int 1) (textObjectRange VimTextObjectRange Inner)] () "")
  (active-command select-surrounding selectSurrounding [(textObject string) (count int 1) (textObjectRange VimTextObjectRange Inner)] () "")
  (active-command move-selection-next moveSelectionNext [(move string) (backwards bool false) (allowEmpty bool false) (count int 1)] () "")
  (active-command move-selection-end moveSelectionEnd [(move string) (backwards bool false) (allowEmpty bool false) (count int 1)] () "")
  (active-command move-paragraph moveParagraph [(backwards bool) (count int 1)] () "")
  (active-command delete-left deleteLeft [] () "")
  (active-command delete-right deleteRight [] () "")
  (active-command move-cursor-page moveCursorPage [(direction int) (count int 1) (center bool false)] () "")
  (active-command move-cursor-visual-page moveCursorVisualPage [(direction int) (count int 1) (center bool false)] () "")
  (active-command move-first moveFirst [(move string)] () "")
  (active-command move-last moveLast [(move string) (count int 1) (wrap bool false)] () "")
  (active-command move move [(move string) (direction int 1) (wrap bool false)] () "")
  (active-command move-direction moveDirection [(move string) (direction int)] () "")
  (active-command move-cursor-line-first-char moveCursorLineFirstChar [(direction int) (count int 1)] () "")
  (active-command move-to-start-of-line moveToStartOfLine [(count int 1)] () "")
  (active-command paste paste [(pasteRight bool false) (inclusiveEnd bool false) (register string "")] () "")
  (active-command toggle-case toggleCase [(moveCursorRight bool)] () "")
  (active-command indent indent [] () "")
  (active-command unindent unindent [] () "")
  (active-command select-prev selectPrev [] () "")
  (active-command select-next selectNext [] () "")
  (active-command add-cursor-above addCursorAbove [] () "")
  (active-command add-cursor-below addCursorBelow [] () "")
  (active-command enter enter [] () "")
  (active-command yank-line yankLine [] () "")
  (active-command delete-line deleteLine [] () "")
  (active-command change-line changeLine [] () "")
  (active-command delete-to-line-end deleteToLineEnd [] () "")
  (active-command change-to-line-end changeToLineEnd [] () "")
  (active-command yank-to-line-end yankToLineEnd [] () "")
  (active-command move-file-start moveFileStart [(count int 1)] () "")
  (active-command move-file-end moveFileEnd [(count int 1)] () "")
  (active-command scroll-line-to-top-and-move-line-start scrollLineToTopAndMoveLineStart [(count int 1)] () "")
  (active-command scroll-line-to-top scrollLineToTop [(count int 1)] () "")
  (active-command center-line-and-move-line-start centerLineAndMoveLineStart [(count int 1)] () "")
  (active-command center-line centerLine [(count int 1)] () "")
  (active-command scroll-line-to-bottom-and-move-line-start scrollLineToBottomAndMoveLineStart [(count int 1)] () "")
  (active-command scroll-line-to-bottom scrollLineToBottom [(count int 1)] () "")
  (active-command insert-mode insertMode [(move string "")] () "")
  (active-command insert-line-below insertLineBelow [] () "")
  (active-command insert-line-above insertLineAbove [(move string "")] () "")
  (active-command set-search-query-from-word setSearchQueryFromWord [] () "")
  (active-command set-search-query-from-selection setSearchQueryFromSelection [] () "")
  (active-command open-search-bar openSearchBar [] () "")
  (active-command select-word-or-add-cursor selectWordOrAddCursor [] () "")
  (active-command move-last-selection-to-next-search-result moveLastSelectionToNextSearchResult [] () "")
  (active-command set-search-query-or-add-cursor setSearchQueryOrAddCursor [] () "")
  (active-command add-mark addMark [(name string)] () "")
  (active-command goto-mark gotoMark [(name string)] () "")
  (active-command delete-word-back deleteWordBack [] () "")
  (active-command delete-line-back deleteLineBack [] () "")
  (active-command surround surround [(text string)] () "")
  (active-command start-macro startMacro [(name string)] () "")
  (active-command play-macro playMacro [(name string)] () "")
  (active-command stop-macro stopMacro [] () "")
  (active-command invert-selections invertSelections [] () "")
  (active-command invert-line-selections invertLineSelections [] () "")
  (active-command reverse-selections reverseSelections [] () "")
  (active-command join-lines joinLines [(reduceSpace bool)] () "")
  (active-command sort-lines sortLines [] () "")
  (active-command move-to-column moveToColumn [(count int 1)] () "")
  (active-command grow-selection growSelection [(amount int 1)] () "")
  (active-command evaluate-selection evaluateSelection [] () "")
  (active-command increment-selection incrementSelection [] () "")
  (active-command decrement-selection decrementSelection [] () "")
  (active-command increment-selection-by-index incrementSelectionByIndex [] () "")
  (active-command increment increment [] () "")
  (active-command decrement decrement [] () "")
  (active-command increment-by-index incrementByIndex [] () "")
  (active-command replace-input-handler replaceInputHandler [(input string)] () "")
)
