# Package

version       = "0.1.1"
author        = "Nimaoth"
description   = "Programming language + editor"
license       = "MIT"
srcDir        = "src"
bin           = @["absytree"]


# Dependencies

requires "nim >= 1.7.3"
requires "chroma >= 0.2.7"
requires "boxy >= 0.4.1"
requires "windy >= 0.0.0"
requires "winim >= 3.8.1"
requires "fusion >= 1.1"
requires "print >= 1.0.2"
requires "fuzzy >= 0.1.0"
requires "lrucache >= 1.1.4"
requires "https://github.com/Nimaoth/nimscripter >= 1.0.17"
requires "https://github.com/Nimaoth/nimtreesitter?subdir=treesitter >= 0.1.1"
requires "https://github.com/Nimaoth/nimtreesitter?subdir=treesitter_c >= 0.1.1"
requires "https://github.com/Nimaoth/nimtreesitter?subdir=treesitter_bash >= 0.1.1"
requires "https://github.com/Nimaoth/nimtreesitter?subdir=treesitter_c_sharp >= 0.1.1"
requires "https://github.com/Nimaoth/nimtreesitter?subdir=treesitter_cpp >= 0.1.1"
# requires "https://github.com/Nimaoth/nimtreesitter?subdir=treesitter_css >= 0.1.1"
# requires "https://github.com/Nimaoth/nimtreesitter?subdir=treesitter_go >= 0.1.1"
# requires "https://github.com/Nimaoth/nimtreesitter?subdir=treesitter_haskell >= 0.1.1"
# requires "https://github.com/Nimaoth/nimtreesitter?subdir=treesitter_html >= 0.1.1"
# requires "https://github.com/Nimaoth/nimtreesitter?subdir=treesitter_java >= 0.1.1"
requires "https://github.com/Nimaoth/nimtreesitter?subdir=treesitter_javascript >= 0.1.1"
# requires "https://github.com/Nimaoth/nimtreesitter?subdir=treesitter_ocaml >= 0.1.1"
# requires "https://github.com/Nimaoth/nimtreesitter?subdir=treesitter_php >= 0.1.1"
# requires "https://github.com/Nimaoth/nimtreesitter?subdir=treesitter_python >= 0.1.1"
# requires "https://github.com/Nimaoth/nimtreesitter?subdir=treesitter_ruby >= 0.1.1"
requires "https://github.com/Nimaoth/nimtreesitter?subdir=treesitter_rust >= 0.1.1"
# requires "https://github.com/Nimaoth/nimtreesitter?subdir=treesitter_scala >= 0.1.1"
# requires "https://github.com/Nimaoth/nimtreesitter?subdir=treesitter_typescript >= 0.1.1"