requires "nim >= 2.2.6"
requires "https://github.com/Nimaoth/vmath#661bdaa"
requires "https://github.com/Nimaoth/pixie >= 5.0.10"
requires "bumpy >= 1.1.2"
requires "chroma >= 0.2.7"
requires "fusion >= 1.2"
requires "https://github.com/nitely/nim-regex#cb8b7bf"
requires "results >= 0.5.0"
requires "https://github.com/Nimaoth/nimwasmtime#2a33f8b"
requires "https://github.com/Nimaoth/nimclay#a834a73"