(
  (inject self Debugger "getServiceChecked(Debugger)")

  (command choose-run-configuration chooseRunConfiguration [] () "")
  (command run-last-configuration runLastConfiguration [] () "")
  (command toggle-debugger-threads toggleDebuggerThreads [(focus bool true) (slot string "#debugger-threads")] () "")
  (command toggle-debugger-stacktrace toggleDebuggerStacktrace [(focus bool true) (slot string "#debugger-stacktrace")] () "")
  (command toggle-debugger-variables toggleDebuggerVariables [(focus bool true) (slot string "#debugger-variables")] () "")
  (command toggle-debugger-output toggleDebuggerOutput [(focus bool true) (slot string "#debugger-output")] () "")
  (command toggle-debugger-toolbar toggleDebuggerToolbar [(focus bool true) (slot string "#debugger-toolbar")] () "")

  (command prev-thread prevThread [] () "")
  (command next-thread nextThread [] () "")
  (command prev-stack-frame prevStackFrame [] () "")
  (command next-stack-frame nextStackFrame [] () "")
  (command open-file-for-current-frame openFileForCurrentFrame [(slot string "")] () "")

  (command evaluate-hover evaluateHover [] () "")
  (command evaluate-mouse-hover evaluateMouseHover [] () "")
  (command add-watch addWatch [(expression string)] () "")
  (command add-watch-prompt addWatchPrompt [] (async) "")
  (command add-watch-from-selection addWatchFromSelection [] () "")
  (command remove-watch removeWatch [(expression string)] () "")
  (command remove-watch-at-cursor removeWatchAtCursor [] () "")

  (command stop-debug-session stopDebugSession [] () "")
  (command stop-debug-session-delayed stopDebugSessionDelayed [] () "")
  (command run-configuration runConfiguration [(name string)] () "")

  (command toggle-breakpoint-at toggleBreakpointAt [(editorId EditorId) (line int)] () "")
  (command toggle-breakpoint toggleBreakpoint [] () "")
  (command remove-breakpoint removeBreakpoint [(path string) (line int)] () "")
  (command toggle-breakpoint-enabled toggleBreakpointEnabled [(path string) (line int)] () "")
  (command toggle-all-breakpoints-enabled toggleAllBreakpointsEnabled [] () "")
  (command toggle-breakpoints-enabled toggleBreakpointsEnabled [] () "")
  (command edit-breakpoints editBreakpoints [] () "")

  (command pause-execution pauseExecution [] () "")
  (command continue-execution continueExecution [] () "")
  (command step-over stepOver [] () "")
  (command step-in stepIn [] () "")
  (command step-out stepOut [] () "")

  (command close-debugger-views closeDebuggerViews [] () "")
  (command close-debugger-threads closeDebuggerThreads [] () "")
  (command close-debugger-stacktrace closeDebuggerStacktrace [] () "")
  (command close-debugger-variables closeDebuggerVariables [] () "")
  (command close-debugger-output closeDebuggerOutput [] () "")
  (command close-debugger-toolbar closeDebuggerToolbar [] () "")

  (command show-debugger-threads showDebuggerThreads [(focus bool true) (slot string "#debugger-threads")] () "")
  (command show-debugger-stacktrace showDebuggerStacktrace [(focus bool true) (slot string "#debugger-stacktrace")] () "")
  (command show-debugger-variables showDebuggerVariables [(focus bool true) (slot string "#debugger-variables")] () "")
  (command show-debugger-output showDebuggerOutput [(focus bool true) (slot string "#debugger-output")] () "")
  (command show-debugger-toolbar showDebuggerToolbar [(focus bool true) (slot string "#debugger-toolbar")] () "")
)
