(
  ; (context layout)

  (inject self LayoutServiceImpl "getServiceChecked(LayoutServiceImpl)")

  (command change-split-size layoutChangeSplitSizeCurrent [(change float) (vertical bool) (add "Option[bool]")] () "")
  (command toggle-maximize-view-local toggleMaximizeViewLocal [(slot string "**")] () "")
  (command toggle-maximize-view toggleMaximizeView [] () "")
  (command set-max-views setMaxViewsCommand [(slot string) (maxViews "Option[int]")] () "")
  (command get-num-visible-views getNumVisibleViews [] int "")
  (command get-num-hidden-views getNumHiddenViews [] int "")
  (command get-or-open-editor getOrOpenEditor [(path string)] "Option[EditorId]" "")
  (command hide-active-view hideActiveViewCommand [(closeOpenPopup "Option[bool]")] () "")
  (command close-active-view closeActiveViewCommand [(closeOpenPopup "Option[bool]") (restoreHidden "Option[bool]")] () "")
  (command hide-other-views hideOtherViews [] () "")
  (command close-other-views closeOtherViews [] () "")
  (command focus-view-left focusViewLeft [] () "")
  (command focus-view-right focusViewRight [] () "")
  (command focus-view-up focusViewUp [] () "")
  (command focus-view-down focusViewDown [] () "")
  (command focus-view layoutServiceFocusView [(slot string)] () "")
  (command focus-next-view focusNextViewCommand [(slot "Option[string]")] () "")
  (command focus-prev-view focusPrevViewCommand [(slot "Option[string]")] () "")
  (command open-prev-view openPrevView [] () "")
  (command open-next-view openNextView [] () "")
  (command open-last-view openLastView [] () "")
  (command set-layout setLayout [(layout string)] () "")
  (command set-active-view-index setActiveViewIndex [(slot string) (index int)] () "")
  (command move-active-view-first moveActiveViewFirst [] () "")
  (command move-active-view-prev moveActiveViewPrev [] () "")
  (command move-active-view-next moveActiveViewNext [] () "")
  (command move-active-view-next-and-go-back moveActiveViewNextAndGoBack [] () "")
  (command split-view splitViewCommand [(slot "Option[string]")] () "")
  (command move-view moveView [(slot string)] () "")
  (command wrap-layout wrapLayoutCommand [(layout JsonNode) (slot "Option[string]")] () "")
  (command pop-popup-into-slot layoutServicePopPopupIntoSlot [(slot string)] () "")
  (command choose-layout chooseLayout [] () "")
  (command log-layout logLayout [] () "")
  (command log-views logViews [] () "")
  (command open openCommand [(path string) (slot "Option[string]")] () "")
  (command choose-open chooseOpenCommand [(preview "Option[bool]") (scaleX "Option[float]") (scaleY "Option[float]") (previewScale "Option[float]")] () "")
)
