
(
  (context editor.text)

  (inject (self text_editor.TextDocumentEditor))

  (active-command enableAutoReload [(enabled bool)] () "")
  (active-command changeLanguage [] () "")
  (active-command setLanguage [(language string "")] () "")
  (active-command evaluateExpressions [(selections Selections) (inclusiveEnd bool false) (prefix string "") (suffix string "") (addSelectionIndex bool false)] () "")
  (active-command setDefaultScrollBehaviour [(scrollBehaviour ScrollBehaviour)] () "")
  (active-command toggleFlag [(key string)] () "")
  (active-command setConfig [(key string) (value JsonNode)] () "")
  (active-command getConfig [(key string)] JsonNode "")
  (active-command removeMode [(mode string)] () "")
  (active-command setMode [(mode string) (exclusive bool true) (forceNotify bool false)] () "")
  (active-command setDefaultMode [(forceNotify bool false)] () "")
  (active-command selectPrev [] () "")
  (active-command selectNext [] () "")
  (active-command printTreesitterMemoryUsage [] () "")
  (active-command printTreesitterTree [] () "")
  (active-command printTreesitterTreeUnderCursor [] () "")
  (active-command selectParentCurrentTs [(includeAfter bool true)] () "")
  (active-command autoShowSignatureHelp [(insertedText string)] () "")
  (active-command autoShowCompletions [] () "")
  (active-command insertText [(text string) (autoIndent bool true) (autoClose "Option[bool]" bool.none)] () "")
  (active-command insertRaw [] () "")
  (active-command indent [] () "")
  (active-command unindent [] () "")
  (active-command insertIndent [] () "")
  (active-command startTransaction [] () "")
  (active-command endTransaction [] () "")
  (active-command undo [(checkpoint string "word")] () "")
  (active-command redo [(checkpoint string "word")] () "")
  (active-command undoToPreviousSibling [(redoUntilBranch bool false)] () "")
  (active-command undoToNextSibling [(redoUntilBranch bool false)] () "")
  (active-command switchUndoBranch [(targetNode int32)] () "")
  (active-command addNextCheckpoint [(checkpoint string)] () "")
  (active-command copy [(register string "") (inclusiveEnd bool false)] () "")
  (active-command paste [(registerName string "") (inclusiveEnd bool false)] () "")
  (active-command pasteAt [(selections "seq[Selection]") (registerName string "") (inclusiveEnd bool false)] () "")
  (active-command scrollText [(amount float32)] () "")
  (active-command scrollTextHorizontal [(amount float32)] () "")
  (active-command scrollLines [(amount int)] () "")
  (active-command addCursorBelow [] () "")
  (active-command addCursorAbove [] () "")
  (active-command closeDiff [] () "")
  (active-command rerender [] () "")
  (active-command clearOverlays [(id int -1)] () "")
  (active-command addOverlay [(selection Selection) (text string) (id int) (scope string) (bias Bias) (renderId int 0) (location overlay_map.OverlayRenderLocation overlay_map.OverlayRenderLocation.Inline)] () "")
  (active-command startDiff [(diffTarget string "") (gotoFirstDiff bool false) (staged bool false)] () "")
  (active-command updateDiff [(gotoFirstDiff bool false)] () "")
  (active-command revertSelected [(inclusiveEnd bool false)] () "")
  (active-command stageSelected [(inclusiveEnd bool false)] () "")
  (active-command stageFile [] () "")
  (active-command format [] () "")
  (active-command checkoutFile [(saveAfterwards bool false)] () "")
  (active-command addFileVcs [] () "")
  (active-command addNextFindResultToSelection [(includeAfter bool true) (wrap bool true)] () "")
  (active-command addPrevFindResultToSelection [(includeAfter bool true) (wrap bool true)] () "")
  (active-command setAllFindResultToSelection [] () "")
  (active-command moveCursorVisualLine [(distance int) (cursor SelectionCursor SelectionCursor.Config) (all bool true) (wrap bool true) (includeAfter bool true)] () "")
  (active-command moveCursorVisualPage [(distance float) (cursor SelectionCursor SelectionCursor.Config) (all bool true) (wrap bool true) (includeAfter bool true)] () "")
  (active-command moveCursorLineCenter [(cursor SelectionCursor SelectionCursor.Config) (all bool true)] () "")
  (active-command moveCursorCenter [(cursor SelectionCursor SelectionCursor.Config) (all bool true)] () "")
  (active-command setDefaultSnapBehaviour [(snapBehaviour ScrollSnapBehaviour)] () "")
  (active-command setCursorScrollOffset [(offset float) (cursor SelectionCursor SelectionCursor.Config)] () "")
  (active-command centerCursor [(cursor SelectionCursor SelectionCursor.Config) (snap bool false)] () "")
  (active-command reloadTreesitter [] () "")
  (active-command clearTreesitterTrees [] () "")
  (active-command runAction [(action string) (args JsonNode)] "Option[JsonNode]" "")
  (active-command deleteMove [(move string) (updateTargetColumn bool true) (options JsonNode "newJObject()" ...)] () "")
  (active-command extendSelectMove [(move string) (inside bool false) (which SelectionCursor SelectionCursor.Config) (all bool true)] () "")
  (active-command move [(move string) (updateTargetColumn bool true) (options JsonNode "newJObject()" ...)] () "")
  (active-command setSearchQuery [(query string) (escapeRegex bool false) (prefix string "") (suffix string "") (useMoveSearch bool false)] bool "")
  (active-command openSearchBar [(query string "") (scrollToPreview bool true) (select bool true) (useMoveSearch bool false)] () "")
  (active-command toggleDebugMoves [] () "")
  (active-command toggleLineComment [] () "")
  (active-command gotoDefinition [(popupSlot string "")] () "")
  (active-command gotoDeclaration [(popupSlot string "")] () "")
  (active-command gotoTypeDefinition [(popupSlot string "")] () "")
  (active-command gotoImplementation [(popupSlot string "")] () "")
  (active-command gotoReferences [(popupSlot string "")] () "")
  (active-command switchSourceHeader [] () "")
  (active-command getCompletions [] () "")
  (active-command gotoSymbol [(popupSlot string "")] () "")
  (active-command fuzzySearchLines [(minScore float 0.2) (sort bool true) (popupSlot string "")] () "")
  (active-command gotoWorkspaceSymbol [(query string "") (popupSlot string "")] () "")
  (active-command rename [] () "")
  (active-command hideCompletions [] () "")
  (active-command selectPrevCompletion [] () "")
  (active-command selectNextCompletion [] () "")
  (active-command selectPrevCompletionVisual [] () "")
  (active-command selectNextCompletionVisual [] () "")
  (active-command clearTabStops [] () "")
  (active-command createCompletionFromSnippet [(snippet JsonNode)] Completion "")
  (active-command applyCompletion [(completion JsonNode)] () "")
  (active-command applySelectedCompletion [] () "")
  (active-command showSignatureHelp [] () "")
  (active-command toggleSignatureHelp [] () "")
  (active-command hideSignatureHelp [] () "")
  (active-command selectCodeAction [] () "")
  (active-command clearDiagnostics [] () "")
  (active-command updateInlayHints [] () "")
  (active-command updateCodeActions [] () "")
  (active-command lspInfo [] () "")
  (active-command setReadOnly [(readOnly bool)] () "")
  (active-command setFileReadOnly [(readOnly bool)] () "")
  (active-command enterChooseCursorMode [(action string)] () "")
  (active-command setCustomHeader [(text string)] () "")
  (active-command cycleSelectedCase [] () "")

)