import std/[strformat, strutils, tables, json, algorithm, sequtils, os]
import ../modules/lisp
import ../src/misc/[case_swap, jsonex, myjsonutils, timer]

proc toNimType(typ: LispVal): string =
  if typ.kind == Symbol:
    typ.sym
  elif typ.kind == String:
    typ.str
  else:
    $typ

proc toNimValue(val: LispVal): string =
  if val.kind == Array:
    return "@[" & val.elems.mapIt(it.toNimValue).join(", ") & "]"
  elif val.kind == List and val.elems.len == 1 and val.elems[0].kind == String:
    return val.elems[0].str
  else:
    $val

proc generateCommands(path: string, input: string) =
  var t = startTimer()
  var nimCode = "# This file is auto generated by tools/command_generator.nim\n\n"
  nimCode.add "import std/[options, json, tables]\nimport misc/[jsonex]\nimport scripting_api\n\n"

  var registerCode = ""
  registerCode.add "proc registerCommands(commands: CommandService) =\n"

  echo "Process ", path
  let debugPrint = false

  type Enum = object
    name: string
    fields: seq[string]

  var enums = initTable[string, Enum]()

  proc markdown(s: string): string = s

  proc escape(s: string): string = s.replace("|", "\\|")
  var docs = newSeq[(string, string)]()

  var lastFullName = ""

  var context = ""
  var injections: seq[(string, string, string)] = @[]
  var numCommands = 0

  let root = parseLispSingle(input)[0]
  for entry in root.elems:
    # echo entry.elems[1]

    case entry.elems[0].sym
    of "context":
      if entry.elems[1].kind == String:
        context = entry.elems[1].str
      if entry.elems[1].kind == Symbol:
        context = entry.elems[1].sym

      registerCode.add &"  const namespace = \"{context}\"\n"

    of "inject":
      let name = entry.elems[1]
      let typ = entry.elems[2]
      let init = entry.elems[3]
      injections.add (name.sym, typ.toNimType(), init.str)

    of "command":
      inc numCommands

      var entryArgIndex = 1

      let rawName = entry.elems[entryArgIndex].sym
      inc entryArgIndex
      let funcName = if entry.elems[entryArgIndex].kind == Symbol:
        inc entryArgIndex
        entry.elems[entryArgIndex - 1].sym
      else:
        rawName

      let params = entry.elems[entryArgIndex]
      inc entryArgIndex
      let ret = entry.elems[entryArgIndex]
      inc entryArgIndex
      let docs = entry.elems[entryArgIndex]
      inc entryArgIndex

      let wrapperName = &"{funcName.toCase(Camel)}Wrapper"
      let commandName = &"{rawName.toCase(Kebab)}"

      nimCode.add &"\nproc {wrapperName}(args: string"
      nimCode.add &"): string"

      let hasReturn = (ret.kind == List and ret.elems.len > 0) or ret.kind == Symbol

      nimCode.add &" =\n"

      # docs
      if docs.str.len > 0:
        var i = 0
        for line in docs.str.splitLines:
          if i == 0 and line.len == 0:
            continue
          nimCode.add "  ## "
          nimCode.add line.strip()
          nimCode.add "\n"
          inc i

      nimCode.add &"  try:\n"
      nimCode.add &"    let args {{.used.}} = args.parseJsonexArgs()\n"
      if debugPrint:
        nimCode.add &"    echo \"Execute command {context}.{commandName}: \", args.unnamed, \", \",  args.named\n"

      for i in 0..injections.high:
        let name = injections[i][0]
        let typ = injections[i][1]
        let init = injections[i][2]
        nimCode.add &"    let {name}: {typ} = {init}\n"

      var callLineStart = nimCode.len
      nimCode.add "    "
      if hasReturn:
        nimCode.add "let res = "

      # call start
      nimCode.add &"{funcName.toCase(Camel)}("

      var numArgs = 0

      # args
      for i in 0..injections.high:
        let name = injections[i][0]
        let typ = injections[i][1]
        if i > 0:
          nimCode.add ","

        let callLineLen = nimCode.len - callLineStart

        var argStr = ""
        argStr.add name

        if callLineLen + argStr.len > 120:
          nimCode.add "\n"
          callLineStart = nimCode.len
          nimCode.add "      "
        elif i > 0:
          nimCode.add " "

        nimCode.add argStr
        inc numArgs

      # args
      for i in 0..params.elems.high:
        let param = params.elems[i]
        let name = param.elems[0].sym
        let typ = param.elems[1]
        let default = if param.elems.len >= 3:
          param.elems[2]
        else:
          nil
        let varargs = if param.elems.len >= 4:
          param.elems[3].sym == "..."
        else:
          false

        if numArgs > 0:
          nimCode.add ","

        let callLineLen = nimCode.len - callLineStart

        var argStr = ""
        let nimTyp = typ.toNimType()

        if varargs:
          argStr.add &"newJexArray(args.unnamed.elems[{i}..^1]).toJson"
        else:
          argStr.add &"getArg[{nimTyp}](args.unnamed, args.named, {i}, \"{name}\""
          if default != nil:
            argStr.add &", {default.toNimValue}"
          argStr.add &")"

        if callLineLen + argStr.len > 120:
          nimCode.add "\n"
          callLineStart = nimCode.len
          nimCode.add "      "
        elif numArgs > 0:
          nimCode.add " "

        nimCode.add argStr
        inc numArgs

      # call end
      nimCode.add(")\n")

      if hasReturn:
        nimCode.add "    return $res.toJsonEx\n"
      else:
        nimCode.add "    return \"\"\n"

      nimCode.add &"  except CatchableError:\n"
      if debugPrint:
        nimCode.add &"    echo \"Failed to execute command {context}.{commandName}: \", getCurrentExceptionMsg(), \" \", getCurrentException().getStackTrace()\n"
      nimCode.add &"    return \"\"\n"

      registerCode.add &"  discard commands.registerCommand(command_service.Command(\n"
      registerCode.add "    "
      if context != "":
        registerCode.add &"namespace: namespace, "
      registerCode.add &"name: \"{commandName}\", execute: {wrapperName},"
      if docs.str.len > 0:
        registerCode.add &"\n    description: \"\"\"{docs.str.strip}\"\"\","
      registerCode.add &"))\n"
    else:
      discard

  nimCode.add "\n"
  nimCode.add registerCode

  let newDir = path.splitPath.head / "generated"
  createDir(newDir)
  let newFile = newDir / path.splitFile.name.replace(".", "_") & ".nim"

  if existsFile(newFile) and readFile(newFile) == nimCode:
    echo "No changes for ", path
    return
  else:
    writeFile(newFile, nimCode)

  echo &"Generated {numCommands} commands in {t.elapsed.ms}ms into {newFile}"

var t = startTimer()
var numFiles = 0
for file in walkDirRec("modules"):
  if file.endsWith(".commands.lisp"):
    inc numFiles
    let f = readFile(file)
    generateCommands(file, f)

echo "Processed ", numFiles, " files in ", t.elapsed.ms, "ms"
