import std/[strformat, strutils, tables, json, algorithm, sequtils]
import ../modules/lisp
import ../src/misc/[case_swap, jsonex, myjsonutils]

proc generateSettings(input: string) =
  var nimCode = "# This file is auto generated by tools/settings_generator.nim\n\n"
  nimCode.add "import std/[options, json, tables]\nimport misc/[jsonex]\nimport config_store, scripting_api\n\n"
  nimCode.add "export config_store\n\n"

  var setDefaults = "# This file is auto generated by tools/settings_generator.nim\n\n"
  setDefaults.add "import std/[options, json, tables]\nimport misc/[jsonex]\nimport config_store\n\n"
  setDefaults.add "export config_store\n\n"
  setDefaults.add &"proc fillDefaultSettings*(s: ConfigStore) =\n"

  type Enum = object
    name: string
    fields: seq[string]

  var enums = initTable[string, Enum]()

  proc markdown(s: string): string = s

  proc escape(s: string): string = s.replace("|", "\\|")
  var docs = newSeq[(string, string)]()

  var lastFullName = ""

  let root = parseLispSingle(input)[0]
  for group in root.elems:
    # echo group.elems[1]

    case group.elems[0].sym
    of "group":
      nimCode.add &"# {group.elems[1]} - {group.elems[2].str}\n"
      let groupName = group.elems[2].str.replace(".", "-").toCase(Pascal)
      for i, s in group.elems:
        if i < 3:
          continue

        var p = ""

        case s.elems[0].sym
        of "setting":
          let typ = s.elems[2].str
          let name = &"{group.elems[2].str}.{s.elems[1]}"
          p = &"proc get{groupName}{s.elems[1].sym.toCase(Pascal)}*(s: ConfigStore, def = {typ}.default): {typ} =\n"
          p.add &"  s.get(\"{name}\", def)\n"

          p.add &"proc set{groupName}{s.elems[1].sym.toCase(Pascal)}*(s: ConfigStore, value: {typ}) =\n"
          p.add &"  s.set(\"{name}\", value)\n"
          nimCode.add p
          nimCode.add "\n"

          if s.elems[3].kind != Nil:
            let defaultValue = if s.elems[3].kind == Symbol:
              $newJString(s.elems[3].sym)
            elif s.elems[3].kind in {Number, Bool, String}:
              $s.elems[3]
            elif s.elems[3].kind in {Nil}:
              ""
            else:
              &"%*{s.elems[3].toJson}"

            setDefaults.add &"  s.set(\"{name}\", {defaultValue})\n"

          let defaultValue = if s.elems[3].kind == Symbol:
            $newJString(s.elems[3].sym)
          elif s.elems[3].kind in {Number, Bool, String}:
            $s.elems[3]
          elif s.elems[3].kind in {Nil}:
            "null"
          else:
            $s.elems[3].toJson

          let settingDocs = s.elems[4].str.replace("\n", " ")
          var typeName = typ
          if typ in enums:
            typeName = enums[typ].fields.mapIt($newJString(it)).join(", ")
          typeName = typeName.replace("RegexSetting", "regex")
          typeName = typeName.replace("JsonNodeEx", "any")
          typeName = typeName.replace("JsonNode", "any")
          typeName = typeName.replace("RuneSetSetting", "seq[string or seq[string]]")

          docs.add (name, "| `" & name & "` | " & typeName.escape() & " | " & defaultValue.escape() & " | " & settingDocs.escape() & " |")

        else:
          discard

    of "enum":
      let name = group.elems[1].sym
      var cases = ""
      var enu = Enum(name: name)
      for i, c in group.elems:
        if i < 2:
          continue
        if i > 2:
          cases.add ", "
        cases.add &"{c.sym.toCase(Pascal)} = \"{c.sym}\""
        enu.fields.add c.sym

      enums[name] = enu
      let t = &"type {name}* {{.pure.}} = enum {cases}\n\n"
      nimCode.add t

    else:
      discard

  docs.sort(proc(a, b: (string, string)): int = cmp(a[0], b[0]))
  var docsString = markdown"""| . | . | . | . |
""" & docs.mapIt(it[1]).join("\n") & "\n"


  var currentDocs = readFile("docs/settings.md")
  let index = currentDocs.find("| . | . | . | . |")
  assert index != -1

  let newDocs = currentDocs[0..<index] & docsString

  writeFile("src/core_settings.nim", nimCode)
  writeFile("src/default_settings.nim", setDefaults)
  writeFile("docs/settings.md", newDocs)

let f = readFile("src/core_settings.lisp")
generateSettings(f)
