# This file is auto generated by tools/settings_generator.nim

import std/[options, json, tables]
import misc/[jsonex]
import config_store, scripting_api

export config_store

type SignColumnShowKind* {.pure.} = enum Auto = "auto", Yes = "yes", No = "no", Number = "number"

type PluginCommandLoadBehaviour* {.pure.} = enum DontRun = "dont-run", AsyncRun = "async-run", WaitAndRun = "wait-and-run", AsyncOrWait = "async-or-wait"

type FormatterInput* {.pure.} = enum TempFile = "temp-file", File = "file", Stdin = "stdin"

type IndentStyleKind* {.pure.} = enum Tabs = "tabs", Spaces = "spaces"

type ColorType* {.pure.} = enum Hex = "hex", Float1 = "float1", Float255 = "float255"

type ScrollToChangeOnReload* {.pure.} = enum First = "first", Last = "last"

type UnsavedBehaviour* {.pure.} = enum None = "none", Temp = "temp", Real = "real"

type ToastStyle* {.pure.} = enum Minimal = "minimal", Box = "box"

type DiagnosticsLocation* {.pure.} = enum LineEnd = "line-end", Below = "below", LineEndOrBelow = "line-end-or-below"

# BackgroundSettings - ui.background
proc getUiBackgroundTransparent*(s: ConfigStore, def = bool.default): bool =
  s.get("ui.background.transparent", def)
proc setUiBackgroundTransparent*(s: ConfigStore, value: bool) =
  s.set("ui.background.transparent", value)

proc getUiBackgroundInactiveBrightnessChange*(s: ConfigStore, def = float.default): float =
  s.get("ui.background.inactive-brightness-change", def)
proc setUiBackgroundInactiveBrightnessChange*(s: ConfigStore, value: float) =
  s.set("ui.background.inactive-brightness-change", value)

# ToastSettings - ui.toast
proc getUiToastStyle*(s: ConfigStore, def = ToastStyle.default): ToastStyle =
  s.get("ui.toast.style", def)
proc setUiToastStyle*(s: ConfigStore, value: ToastStyle) =
  s.set("ui.toast.style", value)

proc getUiToastDuration*(s: ConfigStore, def = int.default): int =
  s.get("ui.toast.duration", def)
proc setUiToastDuration*(s: ConfigStore, value: int) =
  s.set("ui.toast.duration", value)

proc getUiToastAnimation*(s: ConfigStore, def = bool.default): bool =
  s.get("ui.toast.animation", def)
proc setUiToastAnimation*(s: ConfigStore, value: bool) =
  s.set("ui.toast.animation", value)

proc getUiToastMax*(s: ConfigStore, def = int.default): int =
  s.get("ui.toast.max", def)
proc setUiToastMax*(s: ConfigStore, value: int) =
  s.set("ui.toast.max", value)

# UiSettings - ui
proc getUiTheme*(s: ConfigStore, def = string.default): string =
  s.get("ui.theme", def)
proc setUiTheme*(s: ConfigStore, value: string) =
  s.set("ui.theme", value)

proc getUiFontFamily*(s: ConfigStore, def = string.default): string =
  s.get("ui.font-family", def)
proc setUiFontFamily*(s: ConfigStore, value: string) =
  s.set("ui.font-family", value)

proc getUiFontFamilyBold*(s: ConfigStore, def = string.default): string =
  s.get("ui.font-family-bold", def)
proc setUiFontFamilyBold*(s: ConfigStore, value: string) =
  s.set("ui.font-family-bold", value)

proc getUiFontFamilyItalic*(s: ConfigStore, def = string.default): string =
  s.get("ui.font-family-italic", def)
proc setUiFontFamilyItalic*(s: ConfigStore, value: string) =
  s.set("ui.font-family-italic", value)

proc getUiFontFamilyBoldItalic*(s: ConfigStore, def = string.default): string =
  s.get("ui.font-family-bold-italic", def)
proc setUiFontFamilyBoldItalic*(s: ConfigStore, value: string) =
  s.set("ui.font-family-bold-italic", value)

proc getUiWhichKeyDelay*(s: ConfigStore, def = int.default): int =
  s.get("ui.which-key-delay", def)
proc setUiWhichKeyDelay*(s: ConfigStore, value: int) =
  s.set("ui.which-key-delay", value)

proc getUiWhichKeyShowWhenMod*(s: ConfigStore, def = bool.default): bool =
  s.get("ui.which-key-show-when-mod", def)
proc setUiWhichKeyShowWhenMod*(s: ConfigStore, value: bool) =
  s.set("ui.which-key-show-when-mod", value)

proc getUiWhichKeyNoProgress*(s: ConfigStore, def = bool.default): bool =
  s.get("ui.which-key-no-progress", def)
proc setUiWhichKeyNoProgress*(s: ConfigStore, value: bool) =
  s.set("ui.which-key-no-progress", value)

proc getUiWhichKeyHeight*(s: ConfigStore, def = int.default): int =
  s.get("ui.which-key-height", def)
proc setUiWhichKeyHeight*(s: ConfigStore, value: int) =
  s.set("ui.which-key-height", value)

proc getUiPopupWhichKeyHeight*(s: ConfigStore, def = int.default): int =
  s.get("ui.popup-which-key-height", def)
proc setUiPopupWhichKeyHeight*(s: ConfigStore, value: int) =
  s.set("ui.popup-which-key-height", value)

proc getUiMaxViews*(s: ConfigStore, def = int.default): int =
  s.get("ui.max-views", def)
proc setUiMaxViews*(s: ConfigStore, value: int) =
  s.set("ui.max-views", value)

proc getUiSyntaxHighlighting*(s: ConfigStore, def = bool.default): bool =
  s.get("ui.syntax-highlighting", def)
proc setUiSyntaxHighlighting*(s: ConfigStore, value: bool) =
  s.set("ui.syntax-highlighting", value)

proc getUiRainbowParentheses*(s: ConfigStore, def = bool.default): bool =
  s.get("ui.rainbow-parentheses", def)
proc setUiRainbowParentheses*(s: ConfigStore, value: bool) =
  s.set("ui.rainbow-parentheses", value)

proc getUiIndentGuide*(s: ConfigStore, def = bool.default): bool =
  s.get("ui.indent-guide", def)
proc setUiIndentGuide*(s: ConfigStore, value: bool) =
  s.set("ui.indent-guide", value)

proc getUiWhitespaceChar*(s: ConfigStore, def = string.default): string =
  s.get("ui.whitespace-char", def)
proc setUiWhitespaceChar*(s: ConfigStore, value: string) =
  s.set("ui.whitespace-char", value)

proc getUiWhitespaceColor*(s: ConfigStore, def = string.default): string =
  s.get("ui.whitespace-color", def)
proc setUiWhitespaceColor*(s: ConfigStore, value: string) =
  s.set("ui.whitespace-color", value)

proc getUiScrollSpeed*(s: ConfigStore, def = float.default): float =
  s.get("ui.scroll-speed", def)
proc setUiScrollSpeed*(s: ConfigStore, value: float) =
  s.set("ui.scroll-speed", value)

proc getUiSmoothScroll*(s: ConfigStore, def = bool.default): bool =
  s.get("ui.smooth-scroll", def)
proc setUiSmoothScroll*(s: ConfigStore, value: bool) =
  s.set("ui.smooth-scroll", value)

proc getUiSmoothScrollSpeed*(s: ConfigStore, def = float.default): float =
  s.get("ui.smooth-scroll-speed", def)
proc setUiSmoothScrollSpeed*(s: ConfigStore, value: float) =
  s.set("ui.smooth-scroll-speed", value)

proc getUiSmoothScrollSnapThreshold*(s: ConfigStore, def = float.default): float =
  s.get("ui.smooth-scroll-snap-threshold", def)
proc setUiSmoothScrollSnapThreshold*(s: ConfigStore, value: float) =
  s.set("ui.smooth-scroll-snap-threshold", value)

proc getUiCursorTrailSpeed*(s: ConfigStore, def = float.default): float =
  s.get("ui.cursor-trail-speed", def)
proc setUiCursorTrailSpeed*(s: ConfigStore, value: float) =
  s.set("ui.cursor-trail-speed", value)

proc getUiCursorTrailLength*(s: ConfigStore, def = int.default): int =
  s.get("ui.cursor-trail-length", def)
proc setUiCursorTrailLength*(s: ConfigStore, value: int) =
  s.set("ui.cursor-trail-length", value)

proc getUiVsync*(s: ConfigStore, def = bool.default): bool =
  s.get("ui.vsync", def)
proc setUiVsync*(s: ConfigStore, value: bool) =
  s.set("ui.vsync", value)

proc getUiLineNumbers*(s: ConfigStore, def = LineNumbers.default): LineNumbers =
  s.get("ui.line-numbers", def)
proc setUiLineNumbers*(s: ConfigStore, value: LineNumbers) =
  s.set("ui.line-numbers", value)

proc getUiDiagnosticsLocation*(s: ConfigStore, def = DiagnosticsLocation.default): DiagnosticsLocation =
  s.get("ui.diagnostics-location", def)
proc setUiDiagnosticsLocation*(s: ConfigStore, value: DiagnosticsLocation) =
  s.set("ui.diagnostics-location", value)

proc getUiTabHeaderWidth*(s: ConfigStore, def = int.default): int =
  s.get("ui.tab-header-width", def)
proc setUiTabHeaderWidth*(s: ConfigStore, value: int) =
  s.set("ui.tab-header-width", value)

proc getUiHideTabBarWhenSingle*(s: ConfigStore, def = bool.default): bool =
  s.get("ui.hide-tab-bar-when-single", def)
proc setUiHideTabBarWhenSingle*(s: ConfigStore, value: bool) =
  s.set("ui.hide-tab-bar-when-single", value)

proc getUiStatusLine*(s: ConfigStore, def = seq[JsonNodeEx].default): seq[JsonNodeEx] =
  s.get("ui.status-line", def)
proc setUiStatusLine*(s: ConfigStore, value: seq[JsonNodeEx]) =
  s.set("ui.status-line", value)

proc getUiScrollBar*(s: ConfigStore, def = bool.default): bool =
  s.get("ui.scroll-bar", def)
proc setUiScrollBar*(s: ConfigStore, value: bool) =
  s.set("ui.scroll-bar", value)

proc getUiHighlightInlineChanges*(s: ConfigStore, def = bool.default): bool =
  s.get("ui.highlight-inline-changes", def)
proc setUiHighlightInlineChanges*(s: ConfigStore, value: bool) =
  s.set("ui.highlight-inline-changes", value)

# OpenSessionSettings - editor.open-session
proc getEditorOpenSessionUseMultiplexer*(s: ConfigStore, def = bool.default): bool =
  s.get("editor.open-session.use-multiplexer", def)
proc setEditorOpenSessionUseMultiplexer*(s: ConfigStore, value: bool) =
  s.set("editor.open-session.use-multiplexer", value)

proc getEditorOpenSessionCommand*(s: ConfigStore, def = Option[string].default): Option[string] =
  s.get("editor.open-session.command", def)
proc setEditorOpenSessionCommand*(s: ConfigStore, value: Option[string]) =
  s.set("editor.open-session.command", value)

proc getEditorOpenSessionArgs*(s: ConfigStore, def = Option[seq[JsonNodeEx]].default): Option[seq[JsonNodeEx]] =
  s.get("editor.open-session.args", def)
proc setEditorOpenSessionArgs*(s: ConfigStore, value: Option[seq[JsonNodeEx]]) =
  s.set("editor.open-session.args", value)

# GeneralSettings - editor
proc getEditorSaveInSession*(s: ConfigStore, def = bool.default): bool =
  s.get("editor.save-in-session", def)
proc setEditorSaveInSession*(s: ConfigStore, value: bool) =
  s.set("editor.save-in-session", value)

proc getEditorCloseUnusedDocumentsTimer*(s: ConfigStore, def = int.default): int =
  s.get("editor.close-unused-documents-timer", def)
proc setEditorCloseUnusedDocumentsTimer*(s: ConfigStore, value: int) =
  s.set("editor.close-unused-documents-timer", value)

proc getEditorPrintStatisticsOnShutdown*(s: ConfigStore, def = bool.default): bool =
  s.get("editor.print-statistics-on-shutdown", def)
proc setEditorPrintStatisticsOnShutdown*(s: ConfigStore, value: bool) =
  s.set("editor.print-statistics-on-shutdown", value)

proc getEditorMaxSearchResults*(s: ConfigStore, def = int.default): int =
  s.get("editor.max-search-results", def)
proc setEditorMaxSearchResults*(s: ConfigStore, value: int) =
  s.set("editor.max-search-results", value)

proc getEditorMaxSearchResultDisplayLen*(s: ConfigStore, def = int.default): int =
  s.get("editor.max-search-result-display-len", def)
proc setEditorMaxSearchResultDisplayLen*(s: ConfigStore, value: int) =
  s.set("editor.max-search-result-display-len", value)

proc getEditorCustomModeOnTop*(s: ConfigStore, def = bool.default): bool =
  s.get("editor.custom-mode-on-top", def)
proc setEditorCustomModeOnTop*(s: ConfigStore, value: bool) =
  s.set("editor.custom-mode-on-top", value)

proc getEditorClearInputHistoryDelay*(s: ConfigStore, def = int.default): int =
  s.get("editor.clear-input-history-delay", def)
proc setEditorClearInputHistoryDelay*(s: ConfigStore, value: int) =
  s.set("editor.clear-input-history-delay", value)

proc getEditorInsertInputDelay*(s: ConfigStore, def = int.default): int =
  s.get("editor.insert-input-delay", def)
proc setEditorInsertInputDelay*(s: ConfigStore, value: int) =
  s.set("editor.insert-input-delay", value)

proc getEditorRecordInputHistory*(s: ConfigStore, def = bool.default): bool =
  s.get("editor.record-input-history", def)
proc setEditorRecordInputHistory*(s: ConfigStore, value: bool) =
  s.set("editor.record-input-history", value)

proc getEditorWatchTheme*(s: ConfigStore, def = bool.default): bool =
  s.get("editor.watch-theme", def)
proc setEditorWatchTheme*(s: ConfigStore, value: bool) =
  s.set("editor.watch-theme", value)

proc getEditorWatchAppConfig*(s: ConfigStore, def = bool.default): bool =
  s.get("editor.watch-app-config", def)
proc setEditorWatchAppConfig*(s: ConfigStore, value: bool) =
  s.set("editor.watch-app-config", value)

proc getEditorWatchUserConfig*(s: ConfigStore, def = bool.default): bool =
  s.get("editor.watch-user-config", def)
proc setEditorWatchUserConfig*(s: ConfigStore, value: bool) =
  s.set("editor.watch-user-config", value)

proc getEditorWatchWorkspaceConfig*(s: ConfigStore, def = bool.default): bool =
  s.get("editor.watch-workspace-config", def)
proc setEditorWatchWorkspaceConfig*(s: ConfigStore, value: bool) =
  s.set("editor.watch-workspace-config", value)

proc getEditorKeepSessionHistory*(s: ConfigStore, def = bool.default): bool =
  s.get("editor.keep-session-history", def)
proc setEditorKeepSessionHistory*(s: ConfigStore, value: bool) =
  s.set("editor.keep-session-history", value)

proc getEditorPromptBeforeQuit*(s: ConfigStore, def = bool.default): bool =
  s.get("editor.prompt-before-quit", def)
proc setEditorPromptBeforeQuit*(s: ConfigStore, value: bool) =
  s.set("editor.prompt-before-quit", value)

proc getEditorBaseModes*(s: ConfigStore, def = seq[string].default): seq[string] =
  s.get("editor.base-modes", def)
proc setEditorBaseModes*(s: ConfigStore, value: seq[string]) =
  s.set("editor.base-modes", value)

proc getEditorCommandLineModeHigh*(s: ConfigStore, def = string.default): string =
  s.get("editor.command-line-mode-high", def)
proc setEditorCommandLineModeHigh*(s: ConfigStore, value: string) =
  s.set("editor.command-line-mode-high", value)

proc getEditorCommandLineModeLow*(s: ConfigStore, def = string.default): string =
  s.get("editor.command-line-mode-low", def)
proc setEditorCommandLineModeLow*(s: ConfigStore, value: string) =
  s.set("editor.command-line-mode-low", value)

proc getEditorCommandLineResultModeHigh*(s: ConfigStore, def = string.default): string =
  s.get("editor.command-line-result-mode-high", def)
proc setEditorCommandLineResultModeHigh*(s: ConfigStore, value: string) =
  s.set("editor.command-line-result-mode-high", value)

proc getEditorCommandLineResultModeLow*(s: ConfigStore, def = string.default): string =
  s.get("editor.command-line-result-mode-low", def)
proc setEditorCommandLineResultModeLow*(s: ConfigStore, value: string) =
  s.set("editor.command-line-result-mode-low", value)

proc getEditorTreesitterWasmDownloadUrl*(s: ConfigStore, def = string.default): string =
  s.get("editor.treesitter-wasm-download-url", def)
proc setEditorTreesitterWasmDownloadUrl*(s: ConfigStore, value: string) =
  s.set("editor.treesitter-wasm-download-url", value)

# TreesitterSettings - text.treesitter
proc getTextTreesitterEnable*(s: ConfigStore, def = bool.default): bool =
  s.get("text.treesitter.enable", def)
proc setTextTreesitterEnable*(s: ConfigStore, value: bool) =
  s.set("text.treesitter.enable", value)

proc getTextTreesitterPath*(s: ConfigStore, def = Option[string].default): Option[string] =
  s.get("text.treesitter.path", def)
proc setTextTreesitterPath*(s: ConfigStore, value: Option[string]) =
  s.set("text.treesitter.path", value)

proc getTextTreesitterLanguage*(s: ConfigStore, def = Option[string].default): Option[string] =
  s.get("text.treesitter.language", def)
proc setTextTreesitterLanguage*(s: ConfigStore, value: Option[string]) =
  s.set("text.treesitter.language", value)

proc getTextTreesitterQueries*(s: ConfigStore, def = Option[string].default): Option[string] =
  s.get("text.treesitter.queries", def)
proc setTextTreesitterQueries*(s: ConfigStore, value: Option[string]) =
  s.set("text.treesitter.queries", value)

proc getTextTreesitterRepository*(s: ConfigStore, def = Option[string].default): Option[string] =
  s.get("text.treesitter.repository", def)
proc setTextTreesitterRepository*(s: ConfigStore, value: Option[string]) =
  s.set("text.treesitter.repository", value)

# SignColumnSettings - text.signs
proc getTextSignsShow*(s: ConfigStore, def = SignColumnShowKind.default): SignColumnShowKind =
  s.get("text.signs.show", def)
proc setTextSignsShow*(s: ConfigStore, value: SignColumnShowKind) =
  s.set("text.signs.show", value)

proc getTextSignsMaxWidth*(s: ConfigStore, def = int.default): int =
  s.get("text.signs.max-width", def)
proc setTextSignsMaxWidth*(s: ConfigStore, value: int) =
  s.set("text.signs.max-width", value)

# MatchingWordHighlightSettings - text.highlight-matches
proc getTextHighlightMatchesEnable*(s: ConfigStore, def = bool.default): bool =
  s.get("text.highlight-matches.enable", def)
proc setTextHighlightMatchesEnable*(s: ConfigStore, value: bool) =
  s.set("text.highlight-matches.enable", value)

proc getTextHighlightMatchesDelay*(s: ConfigStore, def = int.default): int =
  s.get("text.highlight-matches.delay", def)
proc setTextHighlightMatchesDelay*(s: ConfigStore, value: int) =
  s.set("text.highlight-matches.delay", value)

proc getTextHighlightMatchesMaxSelectionLength*(s: ConfigStore, def = int.default): int =
  s.get("text.highlight-matches.max-selection-length", def)
proc setTextHighlightMatchesMaxSelectionLength*(s: ConfigStore, value: int) =
  s.set("text.highlight-matches.max-selection-length", value)

proc getTextHighlightMatchesMaxSelectionLines*(s: ConfigStore, def = int.default): int =
  s.get("text.highlight-matches.max-selection-lines", def)
proc setTextHighlightMatchesMaxSelectionLines*(s: ConfigStore, value: int) =
  s.set("text.highlight-matches.max-selection-lines", value)

proc getTextHighlightMatchesMaxFileSize*(s: ConfigStore, def = int.default): int =
  s.get("text.highlight-matches.max-file-size", def)
proc setTextHighlightMatchesMaxFileSize*(s: ConfigStore, value: int) =
  s.set("text.highlight-matches.max-file-size", value)

# HoverSettings - text.hover
proc getTextHoverDelay*(s: ConfigStore, def = int.default): int =
  s.get("text.hover.delay", def)
proc setTextHoverDelay*(s: ConfigStore, value: int) =
  s.set("text.hover.delay", value)

proc getTextHoverCommand*(s: ConfigStore, def = JsonNodeEx.default): JsonNodeEx =
  s.get("text.hover.command", def)
proc setTextHoverCommand*(s: ConfigStore, value: JsonNodeEx) =
  s.set("text.hover.command", value)

# InlayHintSettings - text.inlay-hints
proc getTextInlayHintsEnable*(s: ConfigStore, def = bool.default): bool =
  s.get("text.inlay-hints.enable", def)
proc setTextInlayHintsEnable*(s: ConfigStore, value: bool) =
  s.set("text.inlay-hints.enable", value)

# SearchRegexSettings - text.search-regexes
proc getTextSearchRegexesShowOnlyMatchingPart*(s: ConfigStore, def = bool.default): bool =
  s.get("text.search-regexes.show-only-matching-part", def)
proc setTextSearchRegexesShowOnlyMatchingPart*(s: ConfigStore, value: bool) =
  s.set("text.search-regexes.show-only-matching-part", value)

proc getTextSearchRegexesGotoDefinition*(s: ConfigStore, def = Option[RegexSetting].default): Option[RegexSetting] =
  s.get("text.search-regexes.goto-definition", def)
proc setTextSearchRegexesGotoDefinition*(s: ConfigStore, value: Option[RegexSetting]) =
  s.set("text.search-regexes.goto-definition", value)

proc getTextSearchRegexesGotoDeclaration*(s: ConfigStore, def = Option[RegexSetting].default): Option[RegexSetting] =
  s.get("text.search-regexes.goto-declaration", def)
proc setTextSearchRegexesGotoDeclaration*(s: ConfigStore, value: Option[RegexSetting]) =
  s.set("text.search-regexes.goto-declaration", value)

proc getTextSearchRegexesGotoTypeDefinition*(s: ConfigStore, def = Option[RegexSetting].default): Option[RegexSetting] =
  s.get("text.search-regexes.goto-type-definition", def)
proc setTextSearchRegexesGotoTypeDefinition*(s: ConfigStore, value: Option[RegexSetting]) =
  s.set("text.search-regexes.goto-type-definition", value)

proc getTextSearchRegexesGotoImplementation*(s: ConfigStore, def = Option[RegexSetting].default): Option[RegexSetting] =
  s.get("text.search-regexes.goto-implementation", def)
proc setTextSearchRegexesGotoImplementation*(s: ConfigStore, value: Option[RegexSetting]) =
  s.set("text.search-regexes.goto-implementation", value)

proc getTextSearchRegexesGotoReferences*(s: ConfigStore, def = Option[RegexSetting].default): Option[RegexSetting] =
  s.get("text.search-regexes.goto-references", def)
proc setTextSearchRegexesGotoReferences*(s: ConfigStore, value: Option[RegexSetting]) =
  s.set("text.search-regexes.goto-references", value)

proc getTextSearchRegexesSymbols*(s: ConfigStore, def = Option[RegexSetting].default): Option[RegexSetting] =
  s.get("text.search-regexes.symbols", def)
proc setTextSearchRegexesSymbols*(s: ConfigStore, value: Option[RegexSetting]) =
  s.set("text.search-regexes.symbols", value)

proc getTextSearchRegexesWorkspaceSymbols*(s: ConfigStore, def = Option[RegexSetting].default): Option[RegexSetting] =
  s.get("text.search-regexes.workspace-symbols", def)
proc setTextSearchRegexesWorkspaceSymbols*(s: ConfigStore, value: Option[RegexSetting]) =
  s.set("text.search-regexes.workspace-symbols", value)

proc getTextSearchRegexesWorkspaceSymbolsByKind*(s: ConfigStore, def = Option[Table[string, RegexSetting]].default): Option[Table[string, RegexSetting]] =
  s.get("text.search-regexes.workspace-symbols-by-kind", def)
proc setTextSearchRegexesWorkspaceSymbolsByKind*(s: ConfigStore, value: Option[Table[string, RegexSetting]]) =
  s.set("text.search-regexes.workspace-symbols-by-kind", value)

# RipgrepSettings - text.ripgrep
proc getTextRipgrepPassType*(s: ConfigStore, def = bool.default): bool =
  s.get("text.ripgrep.pass-type", def)
proc setTextRipgrepPassType*(s: ConfigStore, value: bool) =
  s.set("text.ripgrep.pass-type", value)

proc getTextRipgrepFileType*(s: ConfigStore, def = Option[string].default): Option[string] =
  s.get("text.ripgrep.file-type", def)
proc setTextRipgrepFileType*(s: ConfigStore, value: Option[string]) =
  s.set("text.ripgrep.file-type", value)

proc getTextRipgrepExtraArgs*(s: ConfigStore, def = seq[string].default): seq[string] =
  s.get("text.ripgrep.extra-args", def)
proc setTextRipgrepExtraArgs*(s: ConfigStore, value: seq[string]) =
  s.set("text.ripgrep.extra-args", value)

# TrimTrailingWhitespaceSettings - text.trim-trailing-whitespace
proc getTextTrimTrailingWhitespaceEnabled*(s: ConfigStore, def = bool.default): bool =
  s.get("text.trim-trailing-whitespace.enabled", def)
proc setTextTrimTrailingWhitespaceEnabled*(s: ConfigStore, value: bool) =
  s.set("text.trim-trailing-whitespace.enabled", value)

proc getTextTrimTrailingWhitespaceMaxSize*(s: ConfigStore, def = int.default): int =
  s.get("text.trim-trailing-whitespace.max-size", def)
proc setTextTrimTrailingWhitespaceMaxSize*(s: ConfigStore, value: int) =
  s.set("text.trim-trailing-whitespace.max-size", value)

# IndentDetectionSettings - text.indent-detection
proc getTextIndentDetectionEnable*(s: ConfigStore, def = bool.default): bool =
  s.get("text.indent-detection.enable", def)
proc setTextIndentDetectionEnable*(s: ConfigStore, value: bool) =
  s.set("text.indent-detection.enable", value)

proc getTextIndentDetectionSamples*(s: ConfigStore, def = int.default): int =
  s.get("text.indent-detection.samples", def)
proc setTextIndentDetectionSamples*(s: ConfigStore, value: int) =
  s.set("text.indent-detection.samples", value)

proc getTextIndentDetectionTimeout*(s: ConfigStore, def = int.default): int =
  s.get("text.indent-detection.timeout", def)
proc setTextIndentDetectionTimeout*(s: ConfigStore, value: int) =
  s.set("text.indent-detection.timeout", value)

# DiffReloadSettings - text.diff-reload
proc getTextDiffReloadEnable*(s: ConfigStore, def = bool.default): bool =
  s.get("text.diff-reload.enable", def)
proc setTextDiffReloadEnable*(s: ConfigStore, value: bool) =
  s.set("text.diff-reload.enable", value)

proc getTextDiffReloadTimeout*(s: ConfigStore, def = int.default): int =
  s.get("text.diff-reload.timeout", def)
proc setTextDiffReloadTimeout*(s: ConfigStore, value: int) =
  s.set("text.diff-reload.timeout", value)

# DiagnosticsSettings - text.diagnostics
proc getTextDiagnosticsEnable*(s: ConfigStore, def = bool.default): bool =
  s.get("text.diagnostics.enable", def)
proc setTextDiagnosticsEnable*(s: ConfigStore, value: bool) =
  s.set("text.diagnostics.enable", value)

proc getTextDiagnosticsSnapshotHistory*(s: ConfigStore, def = int.default): int =
  s.get("text.diagnostics.snapshot-history", def)
proc setTextDiagnosticsSnapshotHistory*(s: ConfigStore, value: int) =
  s.set("text.diagnostics.snapshot-history", value)

# CodeActionSettings - text.code-actions
proc getTextCodeActionsSign*(s: ConfigStore, def = string.default): string =
  s.get("text.code-actions.sign", def)
proc setTextCodeActionsSign*(s: ConfigStore, value: string) =
  s.set("text.code-actions.sign", value)

proc getTextCodeActionsSignWidth*(s: ConfigStore, def = int.default): int =
  s.get("text.code-actions.sign-width", def)
proc setTextCodeActionsSignWidth*(s: ConfigStore, value: int) =
  s.set("text.code-actions.sign-width", value)

proc getTextCodeActionsSignColor*(s: ConfigStore, def = string.default): string =
  s.get("text.code-actions.sign-color", def)
proc setTextCodeActionsSignColor*(s: ConfigStore, value: string) =
  s.set("text.code-actions.sign-color", value)

# ColorHighlightSettings - text.color-highlight
proc getTextColorHighlightEnable*(s: ConfigStore, def = bool.default): bool =
  s.get("text.color-highlight.enable", def)
proc setTextColorHighlightEnable*(s: ConfigStore, value: bool) =
  s.set("text.color-highlight.enable", value)

proc getTextColorHighlightRegex*(s: ConfigStore, def = RegexSetting.default): RegexSetting =
  s.get("text.color-highlight.regex", def)
proc setTextColorHighlightRegex*(s: ConfigStore, value: RegexSetting) =
  s.set("text.color-highlight.regex", value)

proc getTextColorHighlightKind*(s: ConfigStore, def = ColorType.default): ColorType =
  s.get("text.color-highlight.kind", def)
proc setTextColorHighlightKind*(s: ConfigStore, value: ColorType) =
  s.set("text.color-highlight.kind", value)

# TextSettings - text
proc getTextTabWidth*(s: ConfigStore, def = int.default): int =
  s.get("text.tab-width", def)
proc setTextTabWidth*(s: ConfigStore, value: int) =
  s.set("text.tab-width", value)

proc getTextLineComment*(s: ConfigStore, def = Option[string].default): Option[string] =
  s.get("text.line-comment", def)
proc setTextLineComment*(s: ConfigStore, value: Option[string]) =
  s.set("text.line-comment", value)

proc getTextIndentAfter*(s: ConfigStore, def = Option[seq[string]].default): Option[seq[string]] =
  s.get("text.indent-after", def)
proc setTextIndentAfter*(s: ConfigStore, value: Option[seq[string]]) =
  s.set("text.indent-after", value)

proc getTextCompletionWordChars*(s: ConfigStore, def = RuneSetSetting.default): RuneSetSetting =
  s.get("text.completion-word-chars", def)
proc setTextCompletionWordChars*(s: ConfigStore, value: RuneSetSetting) =
  s.set("text.completion-word-chars", value)

proc getTextIndent*(s: ConfigStore, def = IndentStyleKind.default): IndentStyleKind =
  s.get("text.indent", def)
proc setTextIndent*(s: ConfigStore, value: IndentStyleKind) =
  s.set("text.indent", value)

proc getTextAutoReload*(s: ConfigStore, def = bool.default): bool =
  s.get("text.auto-reload", def)
proc setTextAutoReload*(s: ConfigStore, value: bool) =
  s.set("text.auto-reload", value)

proc getTextAddNewFileVcs*(s: ConfigStore, def = bool.default): bool =
  s.get("text.add-new-file-vcs", def)
proc setTextAddNewFileVcs*(s: ConfigStore, value: bool) =
  s.set("text.add-new-file-vcs", value)

proc getTextAddNewFileVcsPrompt*(s: ConfigStore, def = bool.default): bool =
  s.get("text.add-new-file-vcs-prompt", def)
proc setTextAddNewFileVcsPrompt*(s: ConfigStore, value: bool) =
  s.set("text.add-new-file-vcs-prompt", value)

proc getTextInclusiveSelection*(s: ConfigStore, def = bool.default): bool =
  s.get("text.inclusive-selection", def)
proc setTextInclusiveSelection*(s: ConfigStore, value: bool) =
  s.set("text.inclusive-selection", value)

proc getTextCursorMarginRelative*(s: ConfigStore, def = bool.default): bool =
  s.get("text.cursor-margin-relative", def)
proc setTextCursorMarginRelative*(s: ConfigStore, value: bool) =
  s.set("text.cursor-margin-relative", value)

proc getTextCursorMargin*(s: ConfigStore, def = float.default): float =
  s.get("text.cursor-margin", def)
proc setTextCursorMargin*(s: ConfigStore, value: float) =
  s.set("text.cursor-margin", value)

proc getTextWrapLines*(s: ConfigStore, def = bool.default): bool =
  s.get("text.wrap-lines", def)
proc setTextWrapLines*(s: ConfigStore, value: bool) =
  s.set("text.wrap-lines", value)

proc getTextWrapMargin*(s: ConfigStore, def = int.default): int =
  s.get("text.wrap-margin", def)
proc setTextWrapMargin*(s: ConfigStore, value: int) =
  s.set("text.wrap-margin", value)

proc getTextDefaultMode*(s: ConfigStore, def = string.default): string =
  s.get("text.default-mode", def)
proc setTextDefaultMode*(s: ConfigStore, value: string) =
  s.set("text.default-mode", value)

proc getTextSearchWorkspaceRegexMaxResults*(s: ConfigStore, def = int.default): int =
  s.get("text.search-workspace-regex-max-results", def)
proc setTextSearchWorkspaceRegexMaxResults*(s: ConfigStore, value: int) =
  s.set("text.search-workspace-regex-max-results", value)

proc getTextChooseCursorMax*(s: ConfigStore, def = int.default): int =
  s.get("text.choose-cursor-max", def)
proc setTextChooseCursorMax*(s: ConfigStore, value: int) =
  s.set("text.choose-cursor-max", value)

proc getTextControlClickCommand*(s: ConfigStore, def = string.default): string =
  s.get("text.control-click-command", def)
proc setTextControlClickCommand*(s: ConfigStore, value: string) =
  s.set("text.control-click-command", value)

proc getTextControlClickCommandArgs*(s: ConfigStore, def = JsonNode.default): JsonNode =
  s.get("text.control-click-command-args", def)
proc setTextControlClickCommandArgs*(s: ConfigStore, value: JsonNode) =
  s.set("text.control-click-command-args", value)

proc getTextSingleClickCommand*(s: ConfigStore, def = string.default): string =
  s.get("text.single-click-command", def)
proc setTextSingleClickCommand*(s: ConfigStore, value: string) =
  s.set("text.single-click-command", value)

proc getTextSingleClickCommandArgs*(s: ConfigStore, def = JsonNode.default): JsonNode =
  s.get("text.single-click-command-args", def)
proc setTextSingleClickCommandArgs*(s: ConfigStore, value: JsonNode) =
  s.set("text.single-click-command-args", value)

proc getTextDoubleClickCommand*(s: ConfigStore, def = string.default): string =
  s.get("text.double-click-command", def)
proc setTextDoubleClickCommand*(s: ConfigStore, value: string) =
  s.set("text.double-click-command", value)

proc getTextDoubleClickCommandArgs*(s: ConfigStore, def = JsonNode.default): JsonNode =
  s.get("text.double-click-command-args", def)
proc setTextDoubleClickCommandArgs*(s: ConfigStore, value: JsonNode) =
  s.set("text.double-click-command-args", value)

proc getTextTripleClickCommand*(s: ConfigStore, def = string.default): string =
  s.get("text.triple-click-command", def)
proc setTextTripleClickCommand*(s: ConfigStore, value: string) =
  s.set("text.triple-click-command", value)

proc getTextTripleClickCommandArgs*(s: ConfigStore, def = JsonNode.default): JsonNode =
  s.get("text.triple-click-command-args", def)
proc setTextTripleClickCommandArgs*(s: ConfigStore, value: JsonNode) =
  s.set("text.triple-click-command-args", value)

proc getTextScrollToChangeOnReload*(s: ConfigStore, def = Option[bool].default): Option[bool] =
  s.get("text.scroll-to-change-on-reload", def)
proc setTextScrollToChangeOnReload*(s: ConfigStore, value: Option[bool]) =
  s.set("text.scroll-to-change-on-reload", value)

proc getTextScrollToEndOnInsert*(s: ConfigStore, def = bool.default): bool =
  s.get("text.scroll-to-end-on-insert", def)
proc setTextScrollToEndOnInsert*(s: ConfigStore, value: bool) =
  s.set("text.scroll-to-end-on-insert", value)

proc getTextModes*(s: ConfigStore, def = seq[string].default): seq[string] =
  s.get("text.modes", def)
proc setTextModes*(s: ConfigStore, value: seq[string]) =
  s.set("text.modes", value)

proc getTextCompletionMode*(s: ConfigStore, def = string.default): string =
  s.get("text.completion-mode", def)
proc setTextCompletionMode*(s: ConfigStore, value: string) =
  s.set("text.completion-mode", value)

proc getTextHoverMode*(s: ConfigStore, def = string.default): string =
  s.get("text.hover-mode", def)
proc setTextHoverMode*(s: ConfigStore, value: string) =
  s.set("text.hover-mode", value)

proc getTextTabStopMode*(s: ConfigStore, def = string.default): string =
  s.get("text.tab-stop-mode", def)
proc setTextTabStopMode*(s: ConfigStore, value: string) =
  s.set("text.tab-stop-mode", value)

proc getTextModeChangedHandlerCommand*(s: ConfigStore, def = string.default): string =
  s.get("text.mode-changed-handler-command", def)
proc setTextModeChangedHandlerCommand*(s: ConfigStore, value: string) =
  s.set("text.mode-changed-handler-command", value)

proc getTextSignatureHelpEnabled*(s: ConfigStore, def = bool.default): bool =
  s.get("text.signature-help-enabled", def)
proc setTextSignatureHelpEnabled*(s: ConfigStore, value: bool) =
  s.set("text.signature-help-enabled", value)

proc getTextSignatureHelpDelay*(s: ConfigStore, def = int.default): int =
  s.get("text.signature-help-delay", def)
proc setTextSignatureHelpDelay*(s: ConfigStore, value: int) =
  s.set("text.signature-help-delay", value)

proc getTextSignatureHelpMove*(s: ConfigStore, def = string.default): string =
  s.get("text.signature-help-move", def)
proc setTextSignatureHelpMove*(s: ConfigStore, value: string) =
  s.set("text.signature-help-move", value)

proc getTextSignatureHelpTriggerChars*(s: ConfigStore, def = seq[string].default): seq[string] =
  s.get("text.signature-help-trigger-chars", def)
proc setTextSignatureHelpTriggerChars*(s: ConfigStore, value: seq[string]) =
  s.set("text.signature-help-trigger-chars", value)

proc getTextSignatureHelpTriggerOnEditInArgs*(s: ConfigStore, def = bool.default): bool =
  s.get("text.signature-help-trigger-on-edit-in-args", def)
proc setTextSignatureHelpTriggerOnEditInArgs*(s: ConfigStore, value: bool) =
  s.set("text.signature-help-trigger-on-edit-in-args", value)

proc getTextAutoInsertClose*(s: ConfigStore, def = bool.default): bool =
  s.get("text.auto-insert-close", def)
proc setTextAutoInsertClose*(s: ConfigStore, value: bool) =
  s.set("text.auto-insert-close", value)

proc getTextDisableCompletions*(s: ConfigStore, def = bool.default): bool =
  s.get("text.disable-completions", def)
proc setTextDisableCompletions*(s: ConfigStore, value: bool) =
  s.set("text.disable-completions", value)

proc getTextDisableScrolling*(s: ConfigStore, def = bool.default): bool =
  s.get("text.disable-scrolling", def)
proc setTextDisableScrolling*(s: ConfigStore, value: bool) =
  s.set("text.disable-scrolling", value)

# UnsavedSettings - unsaved
proc getUnsavedInterval*(s: ConfigStore, def = int.default): int =
  s.get("unsaved.interval", def)
proc setUnsavedInterval*(s: ConfigStore, value: int) =
  s.set("unsaved.interval", value)

proc getUnsavedBehaviour*(s: ConfigStore, def = UnsavedBehaviour.default): UnsavedBehaviour =
  s.get("unsaved.behaviour", def)
proc setUnsavedBehaviour*(s: ConfigStore, value: UnsavedBehaviour) =
  s.set("unsaved.behaviour", value)

# DebugSettings - debug
proc getDebugLogTextRenderTime*(s: ConfigStore, def = bool.default): bool =
  s.get("debug.log-text-render-time", def)
proc setDebugLogTextRenderTime*(s: ConfigStore, value: bool) =
  s.set("debug.log-text-render-time", value)

proc getDebugDrawTextChunks*(s: ConfigStore, def = bool.default): bool =
  s.get("debug.draw-text-chunks", def)
proc setDebugDrawTextChunks*(s: ConfigStore, value: bool) =
  s.set("debug.draw-text-chunks", value)

proc getDebugLogToInternalDocument*(s: ConfigStore, def = bool.default): bool =
  s.get("debug.log-to-internal-document", def)
proc setDebugLogToInternalDocument*(s: ConfigStore, value: bool) =
  s.set("debug.log-to-internal-document", value)

# LspMergeSettings - lsp-merge
proc getLspMergeTimeout*(s: ConfigStore, def = int.default): int =
  s.get("lsp-merge.timeout", def)
proc setLspMergeTimeout*(s: ConfigStore, value: int) =
  s.set("lsp-merge.timeout", value)

# PluginSettings - plugins
proc getPluginsWatchPluginDirectories*(s: ConfigStore, def = bool.default): bool =
  s.get("plugins.watch-plugin-directories", def)
proc setPluginsWatchPluginDirectories*(s: ConfigStore, value: bool) =
  s.set("plugins.watch-plugin-directories", value)

proc getPluginsCommandLoadBehaviour*(s: ConfigStore, def = PluginCommandLoadBehaviour.default): PluginCommandLoadBehaviour =
  s.get("plugins.command-load-behaviour", def)
proc setPluginsCommandLoadBehaviour*(s: ConfigStore, value: PluginCommandLoadBehaviour) =
  s.set("plugins.command-load-behaviour", value)

# SelectorSettings - selector
proc getSelectorBaseMode*(s: ConfigStore, def = string.default): string =
  s.get("selector.base-mode", def)
proc setSelectorBaseMode*(s: ConfigStore, value: string) =
  s.set("selector.base-mode", value)

proc getSelectorMinScore*(s: ConfigStore, def = float.default): float =
  s.get("selector.min-score", def)
proc setSelectorMinScore*(s: ConfigStore, value: float) =
  s.set("selector.min-score", value)

# TerminalSettings - terminal
proc getTerminalDefaultMode*(s: ConfigStore, def = string.default): string =
  s.get("terminal.default-mode", def)
proc setTerminalDefaultMode*(s: ConfigStore, value: string) =
  s.set("terminal.default-mode", value)

proc getTerminalBaseMode*(s: ConfigStore, def = string.default): string =
  s.get("terminal.base-mode", def)
proc setTerminalBaseMode*(s: ConfigStore, value: string) =
  s.set("terminal.base-mode", value)

proc getTerminalIdleThreshold*(s: ConfigStore, def = int.default): int =
  s.get("terminal.idle-threshold", def)
proc setTerminalIdleThreshold*(s: ConfigStore, value: int) =
  s.set("terminal.idle-threshold", value)

# ContextLineSettings - context-lines
proc getContextLinesEnabled*(s: ConfigStore, def = bool.default): bool =
  s.get("context-lines.enabled", def)
proc setContextLinesEnabled*(s: ConfigStore, value: bool) =
  s.set("context-lines.enabled", value)

proc getContextLinesStyle*(s: ConfigStore, def = string.default): string =
  s.get("context-lines.style", def)
proc setContextLinesStyle*(s: ConfigStore, value: string) =
  s.set("context-lines.style", value)

proc getContextLinesSeparator*(s: ConfigStore, def = string.default): string =
  s.get("context-lines.separator", def)
proc setContextLinesSeparator*(s: ConfigStore, value: string) =
  s.set("context-lines.separator", value)

proc getContextLinesShow*(s: ConfigStore, def = RegexSetting.default): RegexSetting =
  s.get("context-lines.show", def)
proc setContextLinesShow*(s: ConfigStore, value: RegexSetting) =
  s.set("context-lines.show", value)

proc getContextLinesShowConditionals*(s: ConfigStore, def = bool.default): bool =
  s.get("context-lines.show-conditionals", def)
proc setContextLinesShowConditionals*(s: ConfigStore, value: bool) =
  s.set("context-lines.show-conditionals", value)

proc getContextLinesShowClasses*(s: ConfigStore, def = bool.default): bool =
  s.get("context-lines.show-classes", def)
proc setContextLinesShowClasses*(s: ConfigStore, value: bool) =
  s.set("context-lines.show-classes", value)

proc getContextLinesShowFunctions*(s: ConfigStore, def = bool.default): bool =
  s.get("context-lines.show-functions", def)
proc setContextLinesShowFunctions*(s: ConfigStore, value: bool) =
  s.set("context-lines.show-functions", value)

proc getContextLinesShowModules*(s: ConfigStore, def = bool.default): bool =
  s.get("context-lines.show-modules", def)
proc setContextLinesShowModules*(s: ConfigStore, value: bool) =
  s.set("context-lines.show-modules", value)

# FormatSettings - formatter
proc getFormatterOnSave*(s: ConfigStore, def = bool.default): bool =
  s.get("formatter.on-save", def)
proc setFormatterOnSave*(s: ConfigStore, value: bool) =
  s.set("formatter.on-save", value)

proc getFormatterType*(s: ConfigStore, def = string.default): string =
  s.get("formatter.type", def)
proc setFormatterType*(s: ConfigStore, value: string) =
  s.set("formatter.type", value)

proc getFormatterCommand*(s: ConfigStore, def = seq[string].default): seq[string] =
  s.get("formatter.command", def)
proc setFormatterCommand*(s: ConfigStore, value: seq[string]) =
  s.set("formatter.command", value)

proc getFormatterInput*(s: ConfigStore, def = FormatterInput.default): FormatterInput =
  s.get("formatter.input", def)
proc setFormatterInput*(s: ConfigStore, value: FormatterInput) =
  s.set("formatter.input", value)

