package nev:plugins;

interface types {
  record cursor {
    line: s32,
    column: s32,
  }

  record selection {
    first: cursor,
    last: cursor,
  }
}

interface text-editor {
  use types.{cursor, selection};
  // set-selection: func(s: selection);
  get-selection: func() -> selection;
}

interface core {
  bind-keys: func(context: string, sub-context: string, keys: string, action: string, arg: string, description: string, source: tuple<string, s32, s32>);
  define-command: func(name: string, active: bool, docs: string, params: list<tuple<string, string>>, return-type: string, context: string);
  run-command: func(name: string, args: string);
}
interface text {
  use types.{cursor};

  resource rope {
    constructor(content: string);
    clone: func() -> rope;
    text: func() -> string;
    debug: func() -> string;
    slice: func(a: s64, b: s64) -> rope;
    slice-points: func(a: cursor, b: cursor) -> rope;
    get-current-editor-rope: static func() -> rope;
  }
}

world plugin {
  use types.{cursor, selection};

  import text-editor;
  import text;
  import core;

  export init-plugin: func();
  export handle-command: func(name: string, arg: string) -> string;
}
